### PR TITLE
study

### PR DESCRIPTION
**Pull request by mapleDynamicX**
finish homework 1

### CODE REVIEW

**Comment by mapleDynamicX** [comment]
finish homework 1

**Comment by mapleDynamicX** [comment]
i add a new code it can print a pattern with big x,  and you can control its size by input a number,  there are also some file include
my summerize

**Comment by mapleDynamicX** [comment]
I add a new code it can print a pattern with big x, and you can control its size by input a number, there are also some file include
my summarize

**Comment by mapleDynamicX** [comment]
I add a new code it can print a pattern with big x, and you can control its size by input a number, there are also some file include
my summarize second time .

**Comment by mapleDynamicX** [comment]
solve problem

**Comment by 321Aurora** [comment]
作业图片不对哈，而且图片要一起上传，顺便把冲突解决了

**Comment by mapleDynamicX** [comment]
final git homework

**Comment by mapleDynamicX** [comment]
final git homework 2

**Pull request merged**
