### PR TITLE
Xybxy.homework

### PR DESCRIPTION
**Pull request by xybxy123**
This is my homework.

### CODE REVIEW

**Review by xybxy123 — COMMENTED** [review]
I do the git homework.

**Comment by xybxy123** [comment]
@321Aurora Senior.

**Comment by 321Aurora** [comment]
commit 信息最后要有句号 且是描述更改信息的句子

**Comment by xybxy123** [comment]
I have revised.

**Comment by xybxy123** [comment]
> I have revised.

**Comment by xybxy123** [comment]
> commit 信息最后要有句号 且是描述更改信息的句子

I have revised the sentence
/
/
/.

**Comment by 321Aurora** [comment]
看不到你的作业 然后需要解决一下冲突

**Pull request merged**
